/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['LoginInput']
        }
      }
      responses: {
        /** @description Успешный вход */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              user: components['schemas']['User']
              token: string
            }
          }
        }
        /** @description Неверный email или пароль */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/registration': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['RegisterInput']
        }
      }
      responses: {
        /** @description Пользователь успешно создан */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              user: components['schemas']['User']
              token: string
            }
          }
        }
        /** @description Ошибка валидации или email уже занят */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Данные текущего пользователя */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              user: components['schemas']['User']
            }
          }
        }
        /** @description Неавторизован */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/exercises': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          page?: number
          limit?: number
          search?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Список упражнений с пагинацией */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              data: components['schemas']['Exercise'][]
              pagination: components['schemas']['Pagination']
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateExerciseInput']
        }
      }
      responses: {
        /** @description Упражнение создано */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Exercise']
          }
        }
        /** @description Ошибка валидации */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/exercises/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateExerciseInput']
        }
      }
      responses: {
        /** @description Упражнение обновлено */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Exercise']
          }
        }
        /** @description Упражнение не найдено */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Упражнение деактивировано (Soft Delete) */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              message: string
              /** Format: uuid */
              id: string
            }
          }
        }
        /** @description Упражнение не найдено */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/workouts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          page?: number
          limit?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Список тренировок с пагинацией */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              data: components['schemas']['Workout'][]
              pagination: components['schemas']['Pagination']
            }
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateWorkoutInput']
        }
      }
      responses: {
        /** @description Тренировка успешно создана */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Workout']
          }
        }
        /** @description Ошибка валидации */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/workouts/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateWorkoutInput']
        }
      }
      responses: {
        /** @description Тренировка обновлена */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Workout']
          }
        }
        /** @description Тренировка не найдена */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Тренировка удалена (каскадно) */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              message: string
              /** Format: uuid */
              id: string
            }
          }
        }
        /** @description Тренировка не найдена */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/assignments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': components['schemas']['AssignWorkoutInput']
        }
      }
      responses: {
        /** @description Тренировка назначена пользователю */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['WorkoutAssignment']
          }
        }
        /** @description Уже назначена или пользователь не спортсмен */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/assignments/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Мои назначенные тренировки */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              data: components['schemas']['WorkoutAssignment'][]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/assignments/user/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          userId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Назначения конкретного пользователя */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              data: components['schemas']['WorkoutAssignment'][]
              user: {
                /** Format: uuid */
                id: string
                name: string
                /** Format: email */
                email: string
              }
            }
          }
        }
        /** @description Пользователь не найден */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/assignments/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Назначение отменено */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              message: string
              /** Format: uuid */
              id: string
            }
          }
        }
        /** @description Назначение не найдено */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    User: {
      /** Format: uuid */
      id: string
      /** Format: email */
      email: string
      name: string
      /** @enum {string} */
      roleSlug: 'admin' | 'trainer' | 'athlete'
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    Error: {
      error: string
    }
    LoginInput: {
      /**
       * Format: email
       * @description Email пользователя
       * @example test@test.test
       */
      email: string
      /**
       * @description Пароль (минимум 4 символов)
       * @example test
       */
      password: string
    }
    RegisterInput: {
      /**
       * Format: email
       * @example new@test.test
       */
      email: string
      /** @example password123 */
      password: string
      /** @example Иван Иванов */
      name?: string
      /**
       * @description Роль пользователя (admin нельзя создать через API)
       * @default athlete
       * @example athlete
       * @enum {string}
       */
      roleSlug: 'trainer' | 'athlete'
    }
    Exercise: {
      /** Format: uuid */
      id: string
      name: string
      description: string | null
      isActive: boolean
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    Pagination: {
      page: number
      limit: number
      total: number
      totalPages: number
    }
    CreateExerciseInput: {
      /**
       * @description Название упражнения из справочника
       * @example Приседания со штангой
       */
      name: string
      /**
       * @description Описание техники выполнения
       * @example Базовое многосуставное упражнение для развития мышц ног
       */
      description?: string | null
      /**
       * @description Статус активности (true = видно в справочнике)
       * @default true
       * @example true
       */
      isActive: boolean
    }
    UpdateExerciseInput: {
      /**
       * @description Название упражнения из справочника
       * @example Приседания со штангой
       */
      name?: string
      /**
       * @description Описание техники выполнения
       * @example Базовое многосуставное упражнение для развития мышц ног
       */
      description?: string | null
      /**
       * @description Статус активности (true = видно в справочнике)
       * @default true
       * @example true
       */
      isActive: boolean
    }
    Workout: {
      /** Format: uuid */
      id: string
      name: string
      description: string | null
      isActive: boolean
      /** Format: uuid */
      creatorId: string
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
      exercises: components['schemas']['WorkoutExerciseWithDetails'][]
    }
    WorkoutExerciseWithDetails: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      exerciseId: string
      order: number
      sets: number
      repetitions: number
      weight: number
      exercise: components['schemas']['Exercise']
    }
    CreateWorkoutInput: {
      /** @example День ног */
      name: string
      /**
       * @description Описание цели тренировки
       * @example Тяжелая тренировка на низ
       */
      description?: string | null
      /**
       * @default true
       * @example true
       */
      isActive: boolean
      /** @default [] */
      exercises: components['schemas']['WorkoutExerciseItemInput'][]
    }
    WorkoutExerciseItemInput: {
      /**
       * Format: uuid
       * @description UUID упражнения из справочника
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      exerciseId: string
      /**
       * @description Порядок выполнения упражнения
       * @default 1
       * @example 1
       */
      order: number
      /**
       * @description Количество подходов
       * @default 0
       * @example 3
       */
      sets: number
      /**
       * @description Точное число повторений (строго repetitions, не reps)
       * @default 0
       * @example 10
       */
      repetitions: number
      /**
       * @description Рабочий вес в кг (0 для упражнений с собственным весом)
       * @default 0
       * @example 50.5
       */
      weight: number
    }
    UpdateWorkoutInput: {
      /** @example День ног */
      name?: string
      /**
       * @description Описание цели тренировки
       * @example Тяжелая тренировка на низ
       */
      description?: string | null
      /**
       * @default true
       * @example true
       */
      isActive: boolean
      /** @default [] */
      exercises: components['schemas']['WorkoutExerciseItemInput'][]
    }
    WorkoutAssignment: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workoutId: string
      /** Format: uuid */
      userId: string
      /** Format: date-time */
      assignedAt: string
      workout: components['schemas']['Workout']
    }
    AssignWorkoutInput: {
      /**
       * Format: uuid
       * @description UUID шаблона тренировки
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      workoutId: string
      /**
       * Format: uuid
       * @description UUID пользователя (должен быть спортсменом)
       * @example 123e4567-e89b-12d3-a456-426614174001
       */
      userId: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
